/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#00714d",
        "primary-fixed-dim": "#bcc7de",
        "on-primary-container": "#8590a6",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#3c475a",
        "background": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#bcc7de",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffddb8",
        "secondary": "#006c49",
        "primary-container": "#1e293b",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "secondary-container": "#6cf8bb",
        "on-error": "#ffffff",
        "tertiary": "#201100",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45474c",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c5c6cd",
        "on-primary-fixed": "#111c2d",
        "surface-bright": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-tint": "#545f73",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#c88000",
        "tertiary-container": "#3c2300",
        "primary": "#091426",
        "primary-fixed": "#d8e3fb",
        "tertiary-fixed-dim": "#ffb95f",
        "outline": "#75777d",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-fixed": "#2a1700",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-fixed": "#002113",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "xl": "32px",
        "base": "4px",
        "gutter": "24px",
        "md": "16px",
        "xs": "4px",
        "margin-mobile": "16px",
        "lg": "24px",
        "sm": "8px",
        "2xl": "48px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
